server:
    port: 3355
spring:
    profiles:
        active: dev
---
spring:
  profiles: prod
  application:
    name: springcloud-config
  cloud:
     config:
       uri: http://localhost:3344
       label: master
       profile: prod


---
spring:
  profiles: dev
  application:
    name: springcloud-config
  cloud:
     config:
       uri: http://localhost:3344
       label: master
       profile: dev
       
data:
    env: aaaaaa
    user:
        userName: zhangsan
        userId: 1001
        age: 18
        sex: 1
        address: 中山路
        dataSource: db2020