server:
    port:   3344
spring:
    profiles:
        active:
            dev
---
spring:
  profiles: prod
  application:
    name: springcloud-config
  cloud:
     config:
       uri: http://localhost:3344
       label: master
       profile: prod


---
spring:
  profiles: dev
  application:
    name: springcloud-config
  cloud:
     config:
       uri: http://localhost:3344
       label: master
       profile: dev